// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: cloud/api/api.proto

package api

import (
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Authz struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Permission string `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	Insecure   bool   `protobuf:"varint,2,opt,name=insecure,proto3" json:"insecure,omitempty"`
}

func (x *Authz) Reset() {
	*x = Authz{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_api_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Authz) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authz) ProtoMessage() {}

func (x *Authz) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_api_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authz.ProtoReflect.Descriptor instead.
func (*Authz) Descriptor() ([]byte, []int) {
	return file_cloud_api_api_proto_rawDescGZIP(), []int{0}
}

func (x *Authz) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

func (x *Authz) GetInsecure() bool {
	if x != nil {
		return x.Insecure
	}
	return false
}

type AuthzConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config map[string]*AuthzConfig `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *AuthzConfig) Reset() {
	*x = AuthzConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_api_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthzConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthzConfig) ProtoMessage() {}

func (x *AuthzConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_api_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthzConfig.ProtoReflect.Descriptor instead.
func (*AuthzConfig) Descriptor() ([]byte, []int) {
	return file_cloud_api_api_proto_rawDescGZIP(), []int{1}
}

func (x *AuthzConfig) GetConfig() map[string]*AuthzConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type Metadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Credential:
	//	*Metadata_MachineUserApiKey
	Credential isMetadata_Credential `protobuf_oneof:"credential"`
	// Types that are assignable to User:
	//	*Metadata_MachineUser
	User   isMetadata_User `protobuf_oneof:"user"`
	Parent string          `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_api_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_api_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_cloud_api_api_proto_rawDescGZIP(), []int{2}
}

func (m *Metadata) GetCredential() isMetadata_Credential {
	if m != nil {
		return m.Credential
	}
	return nil
}

func (x *Metadata) GetMachineUserApiKey() string {
	if x, ok := x.GetCredential().(*Metadata_MachineUserApiKey); ok {
		return x.MachineUserApiKey
	}
	return ""
}

func (m *Metadata) GetUser() isMetadata_User {
	if m != nil {
		return m.User
	}
	return nil
}

func (x *Metadata) GetMachineUser() string {
	if x, ok := x.GetUser().(*Metadata_MachineUser); ok {
		return x.MachineUser
	}
	return ""
}

func (x *Metadata) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

type isMetadata_Credential interface {
	isMetadata_Credential()
}

type Metadata_MachineUserApiKey struct {
	MachineUserApiKey string `protobuf:"bytes,1,opt,name=machine_user_api_key,json=machineUserApiKey,proto3,oneof"`
}

func (*Metadata_MachineUserApiKey) isMetadata_Credential() {}

type isMetadata_User interface {
	isMetadata_User()
}

type Metadata_MachineUser struct {
	MachineUser string `protobuf:"bytes,2,opt,name=machine_user,json=machineUser,proto3,oneof"`
}

func (*Metadata_MachineUser) isMetadata_User() {}

var file_cloud_api_api_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptor.MethodOptions)(nil),
		ExtensionType: (*Authz)(nil),
		Field:         50000,
		Name:          "cloud.api.authz",
		Tag:           "bytes,50000,opt,name=authz",
		Filename:      "cloud/api/api.proto",
	},
}

// Extension fields to descriptor.MethodOptions.
var (
	// optional cloud.api.Authz authz = 50000;
	E_Authz = &file_cloud_api_api_proto_extTypes[0]
)

var File_cloud_api_api_proto protoreflect.FileDescriptor

var file_cloud_api_api_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x61, 0x70, 0x69,
	0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x43, 0x0a, 0x05, 0x41, 0x75, 0x74, 0x68, 0x7a, 0x12, 0x1e, 0x0a, 0x0a, 0x70,
	0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x69,
	0x6e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69,
	0x6e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x22, 0x9c, 0x01, 0x0a, 0x0b, 0x41, 0x75, 0x74, 0x68,
	0x7a, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x3a, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x7a, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x1a, 0x51, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x41, 0x75, 0x74, 0x68, 0x7a, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x90, 0x01, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x31, 0x0a, 0x14, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x5f, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x11, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x41, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x12, 0x23, 0x0a, 0x0c, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e,
	0x65, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x0b,
	0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x42, 0x0c, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61,
	0x6c, 0x42, 0x06, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x3a, 0x48, 0x0a, 0x05, 0x61, 0x75, 0x74,
	0x68, 0x7a, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0xd0, 0x86, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x7a, 0x52, 0x05, 0x61, 0x75,
	0x74, 0x68, 0x7a, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6e, 0x6f, 0x6b, 0x61, 0x6d, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x65, 0x6d, 0x6f, 0x32,
	0x30, 0x2d, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x61, 0x70, 0x69,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cloud_api_api_proto_rawDescOnce sync.Once
	file_cloud_api_api_proto_rawDescData = file_cloud_api_api_proto_rawDesc
)

func file_cloud_api_api_proto_rawDescGZIP() []byte {
	file_cloud_api_api_proto_rawDescOnce.Do(func() {
		file_cloud_api_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_cloud_api_api_proto_rawDescData)
	})
	return file_cloud_api_api_proto_rawDescData
}

var file_cloud_api_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cloud_api_api_proto_goTypes = []interface{}{
	(*Authz)(nil),                    // 0: cloud.api.Authz
	(*AuthzConfig)(nil),              // 1: cloud.api.AuthzConfig
	(*Metadata)(nil),                 // 2: cloud.api.Metadata
	nil,                              // 3: cloud.api.AuthzConfig.ConfigEntry
	(*descriptor.MethodOptions)(nil), // 4: google.protobuf.MethodOptions
}
var file_cloud_api_api_proto_depIdxs = []int32{
	3, // 0: cloud.api.AuthzConfig.config:type_name -> cloud.api.AuthzConfig.ConfigEntry
	1, // 1: cloud.api.AuthzConfig.ConfigEntry.value:type_name -> cloud.api.AuthzConfig
	4, // 2: cloud.api.authz:extendee -> google.protobuf.MethodOptions
	0, // 3: cloud.api.authz:type_name -> cloud.api.Authz
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	3, // [3:4] is the sub-list for extension type_name
	2, // [2:3] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cloud_api_api_proto_init() }
func file_cloud_api_api_proto_init() {
	if File_cloud_api_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cloud_api_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Authz); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_api_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthzConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_api_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Metadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_cloud_api_api_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Metadata_MachineUserApiKey)(nil),
		(*Metadata_MachineUser)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cloud_api_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_cloud_api_api_proto_goTypes,
		DependencyIndexes: file_cloud_api_api_proto_depIdxs,
		MessageInfos:      file_cloud_api_api_proto_msgTypes,
		ExtensionInfos:    file_cloud_api_api_proto_extTypes,
	}.Build()
	File_cloud_api_api_proto = out.File
	file_cloud_api_api_proto_rawDesc = nil
	file_cloud_api_api_proto_goTypes = nil
	file_cloud_api_api_proto_depIdxs = nil
}
