name: Protobuf

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    container: uber/prototool:1.10.0
    steps:
    - uses: actions/checkout@v2
    - run: prototool format -d .
  go:
    name: protoc-gen-go
    runs-on: ubuntu-latest
    container: nokamotohub/demo20-protoc:latest
    steps:
    - uses: actions/checkout@v2
    - run: chmod u+x ./scripts/build.sh
    - run: ./scripts/build.sh
    - run: chmod u-x ./scripts/build.sh
    - run: git diff --exit-code
